### ISSUE TITLE
Какие оптимизации были реализованы?

### ISSUE THREAD

**Issue by avlechen** [Sanchous19/Compiler#1]

**Comment by Sanchous19** [comment]
Связанные с операциями изменения значения в ячейке, изменения значения счетчика, а также работа с циклами. Вот примеры некоторых из них(на псевдокоде):
`++---+--` -> `-2`
`++>++->+--++-<--+<` -> `+2`
`++---+` -> `nothing`
`[-]` -> `=0`
`[++[-]++[-]]` -> `=0`
`----------[++-[-]+>-++-<-+]++` -> `=2`
